; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Blocks 5
AppVersion=1.2.0
AppPublisher=Scherfgen-Software
AppPublisherURL=https://www.david-scherfgen.de/
AppSupportURL=https://www.david-scherfgen.de/meine-spiele/blocks-5/
AppUpdatesURL=https://www.david-scherfgen.de/meine-spiele/blocks-5/
DefaultDirName={autopf}\Blocks 5
DefaultGroupName=Blocks 5
AllowNoIcons=yes
OutputBaseFilename=blocks-5-1.2.0-setup
SetupIconFile=setupicon.ico
Compression=lzma2/ultra64
SolidCompression=yes
UninstallFilesDir={app}\uninst
UninstallDisplayIcon={app}\blocks5.exe
WizardStyle=modern dynamic
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[CustomMessages]
english.ShowReadme=Show readme file
english.ShowUserDirectory=Show user directory (screenshots, videos, levels)
english.WindowedMode=Blocks 5 (windowed mode)
english.VisitBlocks5Website=Visit Blocks 5 Website
english.VisitScherfgenWebsite=Visit Scherfgen-Software Website
english.UninstallBlocks5=Uninstall Blocks 5
english.EnableUpdateChecker=When launching the game, automatically check for updates
german.ShowReadme=Readme-Datei anzeigen (englisch)
german.ShowUserDirectory=Benutzerverzeichnis anzeigen (Screenshots, Videos, Levels)
german.WindowedMode=Blocks 5 (Fenstermodus)
german.VisitBlocks5Website=Blocks 5-Webseite besuchen
german.VisitScherfgenWebsite=Scherfgen-Software-Webseite besuchen
german.UninstallBlocks5=Blocks 5 deinstallieren
german.EnableUpdateChecker=Beim Starten des Spiels automatisch nach Updates suchen

[Tasks]
Name: "EnableUpdateChecker"; Description: "{cm:EnableUpdateChecker}"; Flags: unchecked; Check: IsFirstInstall
Name: "CreateDesktopIcon"; Description: "{cm:CreateDesktopIcon}"; Flags: unchecked
Name: "ShowReadme"; Description: "{cm:ShowReadme}"

; The two .bat files are left behind by versions before 1.2.0, which switched
; the update check with them; the switch is in the game's options now.
; .update_checker is an earlier installation's answer to the EnableUpdateChecker
; box, which an installation for all users leaves where the game cannot delete
; it. An update says nothing, so it has to go before the game sees it again.
[InstallDelete]
Type: files; Name: "{app}\update_checker_disable.bat"
Type: files; Name: "{app}\update_checker_enable.bat"
Type: files; Name: "{app}\.update_checker"

[Files]
Source: "..\stage\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\Blocks 5"; Filename: "{app}\blocks5.exe"; WorkingDir: "{app}"

Name: "{group}\{cm:ShowReadme}"; Filename: "{app}\readme.txt"
Name: "{group}\{cm:ShowUserDirectory}"; Filename: "{app}\showuserdir.exe"
Name: "{group}\{cm:WindowedMode}"; Filename: "{app}\blocks5.exe"; Parameters: "-windowed"; WorkingDir: "{app}"
Name: "{group}\{cm:VisitBlocks5Website}"; Filename: "{app}\Blocks 5 Website.url"; WorkingDir: "{app}"
Name: "{group}\{cm:VisitScherfgenWebsite}"; Filename: "{app}\Scherfgen-Software Website.url"; WorkingDir: "{app}"
Name: "{group}\{cm:UninstallBlocks5}"; Filename: "{uninstallexe}"
Name: "{userdesktop}\Blocks 5"; Filename: "{app}\blocks5.exe"; WorkingDir: "{app}"; Tasks: CreateDesktopIcon

[Run]
Filename: "notepad.exe"; Parameters: "{app}\readme.txt"; Flags: nowait; Tasks: ShowReadme
Filename: "{app}\blocks5.exe"; Description: "{cm:LaunchProgram,Blocks 5}"; Flags: nowait postinstall skipifsilent

; Written by the code below, so the uninstaller does not know of it by itself.
[UninstallDelete]
Type: files; Name: "{app}\.update_checker"

[Code]
var
  FirstInstall: Boolean;

// Whether Blocks 5 has been installed here before, by the uninstaller's key: in
// the machine's hive or the user's, after how the earlier installation ran.
// AppId is not set, so Inno names the key after AppName, as it always has.
// Asked before anything is installed, because the installation writes the key.
function InitializeSetup: Boolean;
var
  Key: String;
begin
  Key := 'Software\Microsoft\Windows\CurrentVersion\Uninstall\Blocks 5_is1';
  FirstInstall := not RegKeyExists(HKLM, Key) and not RegKeyExists(HKCU, Key);
  Result := True;
end;

// The update check's box is offered on a first installation only. On an update
// the player has a setting of their own in the game's options, and a box would
// overrule it whichever way it started, for anybody who just clicked through.
function IsFirstInstall: Boolean;
begin
  Result := FirstInstall;
end;

// The update check is the game's own setting, in config.xml. On a first
// installation the installer leaves the box's answer beside the game, ticked
// or not, and the game takes it in at its first start and deletes the file
// where it may (main.cpp, adoptUpdateCheckChoices). On an update it writes
// nothing at all, and [InstallDelete] has taken away an earlier answer.
procedure CurStepChanged(CurStep: TSetupStep);
var
  Choice: String;
begin
  if (CurStep = ssPostInstall) and FirstInstall then
  begin
    if WizardIsTaskSelected('EnableUpdateChecker') then Choice := '1' else Choice := '0';
    SaveStringToFile(ExpandConstant('{app}\.update_checker'), Choice, False);
  end;
end;
