; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Blocks 5
AppVersion=1.2.0
AppPublisher=Scherfgen-Software
AppPublisherURL=https://www.david-scherfgen.de/
AppSupportURL=https://www.david-scherfgen.de/meine-spiele/blocks-5/
AppUpdatesURL=https://www.david-scherfgen.de/meine-spiele/blocks-5/
DefaultDirName={autopf}\Blocks 5
DefaultGroupName=Blocks 5
AllowNoIcons=yes
OutputBaseFilename=blocks-5-1.2.0-setup
SetupIconFile=setupicon.ico
Compression=lzma2/ultra64
SolidCompression=yes
UninstallFilesDir={app}\uninst
UninstallDisplayIcon={app}\blocks5.exe
WizardStyle=modern dynamic
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[CustomMessages]
english.ShowReadme=Show readme file
english.ShowUserDirectory=Show user directory (screenshots, videos, levels)
english.WindowedMode=Blocks 5 (windowed mode)
english.VisitBlocks5Website=Visit Blocks 5 Website
english.VisitScherfgenWebsite=Visit Scherfgen-Software Website
english.UninstallBlocks5=Uninstall Blocks 5
english.EnableUpdateChecker=Enable checking for updates by default
german.ShowReadme=Readme-Datei anzeigen (englisch)
german.ShowUserDirectory=Benutzerverzeichnis anzeigen (Screenshots, Videos, Levels)
german.WindowedMode=Blocks 5 (Fenstermodus)
german.VisitBlocks5Website=Blocks 5-Webseite besuchen
german.VisitScherfgenWebsite=Scherfgen-Software-Webseite besuchen
german.UninstallBlocks5=Blocks 5 deinstallieren
german.EnableUpdateChecker=Update-Suche als Voreinstellung einschalten

[Tasks]
; Not EnableUpdateChecker, the name 1.1.x gave a task that was ticked unless
; cleared: Setup takes a task's selection from the installation before by its
; name, and would tick this one for nearly everybody updating from 1.1.x.
Name: "UpdateCheckDefault"; Description: "{cm:EnableUpdateChecker}"; Flags: unchecked
Name: "CreateDesktopIcon"; Description: "{cm:CreateDesktopIcon}"; Flags: unchecked
Name: "ShowReadme"; Description: "{cm:ShowReadme}"

; Left behind by versions before 1.2.0, which switched the update check with
; them; each player switches it in the game's options now.
[InstallDelete]
Type: files; Name: "{app}\update_checker_disable.bat"
Type: files; Name: "{app}\update_checker_enable.bat"

[Files]
Source: "..\stage\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\Blocks 5"; Filename: "{app}\blocks5.exe"; WorkingDir: "{app}"

Name: "{group}\{cm:ShowReadme}"; Filename: "{app}\readme.txt"
Name: "{group}\{cm:ShowUserDirectory}"; Filename: "{app}\showuserdir.exe"
Name: "{group}\{cm:WindowedMode}"; Filename: "{app}\blocks5.exe"; Parameters: "-windowed"; WorkingDir: "{app}"
Name: "{group}\{cm:VisitBlocks5Website}"; Filename: "{app}\Blocks 5 Website.url"; WorkingDir: "{app}"
Name: "{group}\{cm:VisitScherfgenWebsite}"; Filename: "{app}\Scherfgen-Software Website.url"; WorkingDir: "{app}"
Name: "{group}\{cm:UninstallBlocks5}"; Filename: "{uninstallexe}"
Name: "{userdesktop}\Blocks 5"; Filename: "{app}\blocks5.exe"; WorkingDir: "{app}"; Tasks: CreateDesktopIcon

[Run]
Filename: "notepad.exe"; Parameters: "{app}\readme.txt"; Flags: nowait; Tasks: ShowReadme
Filename: "{app}\blocks5.exe"; Description: "{cm:LaunchProgram,Blocks 5}"; Flags: nowait postinstall skipifsilent

; Written by the code below and by the game, so the uninstaller does not know
; of them by itself: SDL sends what the game prints to stdout.txt beside it,
; and leaves the file there where it is not empty, as it leaves stderr.txt
; after a crash.
[UninstallDelete]
Type: files; Name: "{app}\.update_checker"
Type: files; Name: "{app}\stdout.txt"
Type: files; Name: "{app}\stderr.txt"

[Code]
// The UpdateCheckDefault box sets the installation's default for the update
// check, ticked or not, as .update_checker beside the game: '1' or '0'. Every
// player starts with it, until their config.xml holds a setting of their own,
// which it does from their first exit on (Engine::loadConfig). Written on
// every installation, an update's included, and left there for the next new
// player.
procedure CurStepChanged(CurStep: TSetupStep);
var
  Choice: String;
begin
  if CurStep = ssPostInstall then
  begin
    if WizardIsTaskSelected('UpdateCheckDefault') then Choice := '1' else Choice := '0';
    SaveStringToFile(ExpandConstant('{app}\.update_checker'), Choice, False);
  end;
end;
