#ifndef XBR_LV2_H
#define XBR_LV2_H

/*
   Hyllian's xBR-lv2 Shader

   Copyright (C) 2011-2016 Hyllian - sergiogdb@gmail.com

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in
   all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
   THE SOFTWARE.
*/

/* Ported from the libretro GLSL version; PROVENANCE.txt lists every change.
   No #version directive: the default is 110 on desktop GL and 100 on GLSL ES,
   and this source compiles as either.

   small_details is a uniform, the way RetroArch exposes it when it defines
   PARAMETER_UNIFORM. Both of upstream's paths are here. */

static const char* p_xbrVertexShader =
	"#ifdef GL_ES\n"
	"precision highp float;\n"
	"#endif\n"
	"attribute vec2 aPosition;\n"
	"attribute vec2 aTexCoord;\n"
	"varying vec2 texCoord;\n"
	"void main()\n"
	"{\n"
	"    texCoord = aTexCoord;\n"
	"    gl_Position = vec4(aPosition, 0.0, 1.0);\n"
	"}\n";

static const char* p_xbrFragmentShader =
	"#ifdef GL_ES\n"
	"#ifdef GL_FRAGMENT_PRECISION_HIGH\n"
	"precision highp float;\n"
	"#else\n"
	"precision mediump float;\n"
	"#endif\n"
	"#endif\n"
	"#define FragColor gl_FragColor\n"
	"#define tex2D texture2D\n"
	"#define XBR_SCALE 3.0\n"
	"#define XBR_Y_WEIGHT 48.0\n"
	"#define XBR_EQ_THRESHOLD 15.0\n"
	"#define XBR_LV2_COEFFICIENT 2.0\n"
	"#define lv2_cf XBR_LV2_COEFFICIENT\n"
	"#define CORNER_C\n"
	"#define SMOOTH_TIPS\n"
	"uniform sampler2D decal;\n"
	"uniform vec2 TextureSize;\n"
	"uniform float small_details;\n"
	"varying vec2 texCoord;\n"
	"const float coef         = 2.0;\n"
	"const vec3 rgbw          = vec3(14.352, 28.176, 5.472);\n"
	"const vec4 eq_threshold  = vec4(15.0, 15.0, 15.0, 15.0);\n"
	"\n"
	"const vec4 delta   = vec4(1.0/XBR_SCALE, 1.0/XBR_SCALE, 1.0/XBR_SCALE, 1.0/XBR_SCALE);\n"
	"const vec4 delta_l = vec4(0.5/XBR_SCALE, 1.0/XBR_SCALE, 0.5/XBR_SCALE, 1.0/XBR_SCALE);\n"
	"const vec4 delta_u = vec4(1.0/XBR_SCALE, 0.5/XBR_SCALE, 1.0/XBR_SCALE, 0.5/XBR_SCALE);\n"
	"\n"
	"const  vec4 Ao = vec4( 1.0, -1.0, -1.0, 1.0 );\n"
	"const  vec4 Bo = vec4( 1.0,  1.0, -1.0,-1.0 );\n"
	"const  vec4 Co = vec4( 1.5,  0.5, -0.5, 0.5 );\n"
	"const  vec4 Ax = vec4( 1.0, -1.0, -1.0, 1.0 );\n"
	"const  vec4 Bx = vec4( 0.5,  2.0, -0.5,-2.0 );\n"
	"const  vec4 Cx = vec4( 1.0,  1.0, -0.5, 0.0 );\n"
	"const  vec4 Ay = vec4( 1.0, -1.0, -1.0, 1.0 );\n"
	"const  vec4 By = vec4( 2.0,  0.5, -2.0,-0.5 );\n"
	"const  vec4 Cy = vec4( 2.0,  0.0, -1.0, 0.5 );\n"
	"const  vec4 Ci = vec4(0.25, 0.25, 0.25, 0.25);\n"
	"\n"
	"const vec3 Y = vec3(0.2126, 0.7152, 0.0722);\n"
	"\n"
	"// Difference between vector components.\n"
	"vec4 df(vec4 A, vec4 B)\n"
	"{\n"
	"    return vec4(abs(A-B));\n"
	"}\n"
	"\n"
	"// Compare two vectors and return their components are different.\n"
	"vec4 diff(vec4 A, vec4 B)\n"
	"{\n"
	"    return vec4(notEqual(A, B));\n"
	"}\n"
	"\n"
	"// Determine if two vector components are equal based on a threshold.\n"
	"vec4 eq(vec4 A, vec4 B)\n"
	"{\n"
	"    return (step(df(A, B), vec4(XBR_EQ_THRESHOLD)));\n"
	"}\n"
	"\n"
	"// Determine if two vector components are NOT equal based on a threshold.\n"
	"vec4 neq(vec4 A, vec4 B)\n"
	"{\n"
	"    return (vec4(1.0, 1.0, 1.0, 1.0) - eq(A, B));\n"
	"}\n"
	"\n"
	"// Weighted distance.\n"
	"vec4 wd(vec4 a, vec4 b, vec4 c, vec4 d, vec4 e, vec4 f, vec4 g, vec4 h)\n"
	"{\n"
	"    return (df(a,b) + df(a,c) + df(d,e) + df(d,f) + 4.0*df(g,h));\n"
	"}\n"
	"\n"
	"vec4 weighted_distance(vec4 a, vec4 b, vec4 c, vec4 d, vec4 e, vec4 f, vec4 g, vec4 h, vec4 i, vec4 j, vec4 k, vec4 l)\n"
	"{\n"
	"	return (df(a,b) + df(a,c) + df(d,e) + df(d,f) + df(i,j) + df(k,l) + 2.0*df(g,h));\n"
	"}\n"
	"\n"
	"float c_df(vec3 c1, vec3 c2) \n"
	"{\n"
	"      vec3 df = abs(c1 - c2);\n"
	"      return df.r + df.g + df.b;\n"
	"}\n"
	"\n"
	"\n"
	"void main()\n"
	"{\n"
	"    vec4 edri, edr, edr_l, edr_u, px; // px = pixel, edr = edge detection rule\n"
	"    vec4 irlv0, irlv1, irlv2l, irlv2u, block_3d;\n"
	"    vec4 fx, fx_l, fx_u; // inequations of straight lines.\n"
	"\n"
	"    vec2 fp  = fract(texCoord*TextureSize);\n"
	"\n"
	"    float dx = 1.0/TextureSize.x;\n"
	"    float dy = 1.0/TextureSize.y;\n"
	"    vec2  TexCoord = texCoord;\n"
	"    vec4  t1, t2, t3, t4, t5, t6, t7;\n"
	"    t1 = TexCoord.xxxy + vec4( -dx, 0, dx,-2.0*dy); // A1 B1 C1\n"
	"    t2 = TexCoord.xxxy + vec4( -dx, 0, dx,    -dy); //  A  B  C\n"
	"    t3 = TexCoord.xxxy + vec4( -dx, 0, dx,      0); //  D  E  F\n"
	"    t4 = TexCoord.xxxy + vec4( -dx, 0, dx,     dy); //  G  H  I\n"
	"    t5 = TexCoord.xxxy + vec4( -dx, 0, dx, 2.0*dy); // G5 H5 I5\n"
	"    t6 = TexCoord.xyyy + vec4(-2.0*dx,-dy, 0,  dy); // A0 D0 G0\n"
	"    t7 = TexCoord.xyyy + vec4( 2.0*dx,-dy, 0,  dy); // C4 F4 I4\n"
	"\n"
	"    vec3 A1 = tex2D(decal, t1.xw ).xyz;\n"
	"    vec3 B1 = tex2D(decal, t1.yw ).xyz;\n"
	"    vec3 C1 = tex2D(decal, t1.zw ).xyz;\n"
	"    vec3 A  = tex2D(decal, t2.xw ).xyz;\n"
	"    vec3 B  = tex2D(decal, t2.yw ).xyz;\n"
	"    vec3 C  = tex2D(decal, t2.zw ).xyz;\n"
	"    vec3 D  = tex2D(decal, t3.xw ).xyz;\n"
	"    vec3 E  = tex2D(decal, t3.yw ).xyz;\n"
	"    vec3 F  = tex2D(decal, t3.zw ).xyz;\n"
	"    vec3 G  = tex2D(decal, t4.xw ).xyz;\n"
	"    vec3 H  = tex2D(decal, t4.yw ).xyz;\n"
	"    vec3 I  = tex2D(decal, t4.zw ).xyz;\n"
	"    vec3 G5 = tex2D(decal, t5.xw ).xyz;\n"
	"    vec3 H5 = tex2D(decal, t5.yw ).xyz;\n"
	"    vec3 I5 = tex2D(decal, t5.zw ).xyz;\n"
	"    vec3 A0 = tex2D(decal, t6.xy ).xyz;\n"
	"    vec3 D0 = tex2D(decal, t6.xz ).xyz;\n"
	"    vec3 G0 = tex2D(decal, t6.xw ).xyz;\n"
	"    vec3 C4 = tex2D(decal, t7.xy ).xyz;\n"
	"    vec3 F4 = tex2D(decal, t7.xz ).xyz;\n"
	"    vec3 I4 = tex2D(decal, t7.xw ).xyz;\n"
	"\n"
	"    vec4 b  = vec4(dot(B ,rgbw), dot(D ,rgbw), dot(H ,rgbw), dot(F ,rgbw));\n"
	"    vec4 c  = vec4(dot(C ,rgbw), dot(A ,rgbw), dot(G ,rgbw), dot(I ,rgbw));\n"
	"    vec4 d  = b.yzwx;\n"
	"    vec4 e  = vec4(dot(E,rgbw));\n"
	"    vec4 f  = b.wxyz;\n"
	"    vec4 g  = c.zwxy;\n"
	"    vec4 h  = b.zwxy;\n"
	"    vec4 i  = c.wxyz;\n"
	"    \n"
	"	vec4 i4, i5, h5, f4;\n"
	"	\n"
	"	float y_weight = XBR_Y_WEIGHT;\n"
	"	\n"
	"	vec3 wgt = (small_details < 0.5) ? rgbw : (y_weight * Y);\n"
	"	i4 = vec4(dot(I4,wgt), dot(C1,wgt), dot(A0,wgt), dot(G5,wgt));\n"
	"	i5 = vec4(dot(I5,wgt), dot(C4,wgt), dot(A1,wgt), dot(G0,wgt));\n"
	"	h5 = vec4(dot(H5,wgt), dot(F4,wgt), dot(B1,wgt), dot(D0,wgt));\n"
	"\n"
	"    // These inequations define the line below which interpolation occurs.\n"
	"    fx   = (Ao*fp.y+Bo*fp.x); \n"
	"    fx_l = (Ax*fp.y+Bx*fp.x);\n"
	"    fx_u = (Ay*fp.y+By*fp.x);\n"
	"\n"
	"    irlv1 = irlv0 = diff(e,f) * diff(e,h);\n"
	"\n"
	"#ifdef CORNER_B\n"
	"    irlv1      = (irlv0 * ( neq(f,b) * neq(h,d) + eq(e,i) * neq(f,i4) * neq(h,i5) + eq(e,g) + eq(e,c) ) );\n"
	"#endif\n"
	"#ifdef CORNER_D\n"
	"    vec4 c1 = i4.yzwx;\n"
	"    vec4 g0 = i5.wxyz;\n"
	"    irlv1     = (irlv0  *  ( neq(f,b) * neq(h,d) + eq(e,i) * neq(f,i4) * neq(h,i5) + eq(e,g) + eq(e,c) ) * (diff(f,f4) * diff(f,i) + diff(h,h5) * diff(h,i) + diff(h,g) + diff(f,c) + eq(b,c1) * eq(d,g0)));\n"
	"#endif\n"
	"#ifdef CORNER_C\n"
	"    irlv1     = (irlv0  * ( neq(f,b) * neq(f,c) + neq(h,d) * neq(h,g) + eq(e,i) * (neq(f,f4) * neq(f,i4) + neq(h,h5) * neq(h,i5)) + eq(e,g) + eq(e,c)) );\n"
	"#endif\n"
	"\n"
	"    irlv2l = diff(e,g) * diff(d,g);\n"
	"    irlv2u = diff(e,c) * diff(b,c);\n"
	"\n"
	"    vec4 fx45i = clamp((fx   + delta   -Co - Ci)/(2.0*delta  ), 0.0, 1.0);\n"
	"    vec4 fx45  = clamp((fx   + delta   -Co     )/(2.0*delta  ), 0.0, 1.0);\n"
	"    vec4 fx30  = clamp((fx_l + delta_l -Cx     )/(2.0*delta_l), 0.0, 1.0);\n"
	"    vec4 fx60  = clamp((fx_u + delta_u -Cy     )/(2.0*delta_u), 0.0, 1.0);\n"
	"\n"
	"    vec4 wd1, wd2;\n"
	"	if (small_details < 0.5)\n"
	"	{\n"
	"		wd1 = wd( e, c,  g, i, h5, f4, h, f);\n"
	"		wd2 = wd( h, d, i5, f, i4,  b, e, i);\n"
	"	}\n"
	"	else\n"
	"	{\n"
	"		wd1 = weighted_distance( e, c, g, i, f4, h5, h, f, b, d, i4, i5);\n"
	"		wd2 = weighted_distance( h, d, i5, f, b, i4, e, i, g, h5, c, f4);\n"
	"	}\n"
	"\n"
	"    edri  = step(wd1, wd2) * irlv0;\n"
	"    edr   = step(wd1 + vec4(0.1, 0.1, 0.1, 0.1), wd2) * step(vec4(0.5, 0.5, 0.5, 0.5), irlv1);\n"
	"    edr_l = step( lv2_cf*df(f,g), df(h,c) ) * irlv2l * edr;\n"
	"    edr_u = step( lv2_cf*df(h,c), df(f,g) ) * irlv2u * edr;\n"
	"\n"
	"    fx45  = edr   * fx45;\n"
	"    fx30  = edr_l * fx30;\n"
	"    fx60  = edr_u * fx60;\n"
	"    fx45i = edri  * fx45i;\n"
	"\n"
	"    px = step(df(e,f), df(e,h));\n"
	"\n"
	"#ifdef SMOOTH_TIPS\n"
	"    vec4 maximos = max(max(fx30, fx60), max(fx45, fx45i));\n"
	"#endif\n"
	"#ifndef SMOOTH_TIPS\n"
	"    vec4 maximos = max(max(fx30, fx60), fx45);\n"
	"#endif\n"
	"\n"
	"    vec3 res1 = E;\n"
	"    res1 = mix(res1, mix(H, F, px.x), maximos.x);\n"
	"    res1 = mix(res1, mix(B, D, px.z), maximos.z);\n"
	"    \n"
	"    vec3 res2 = E;\n"
	"    res2 = mix(res2, mix(F, B, px.y), maximos.y);\n"
	"    res2 = mix(res2, mix(D, H, px.w), maximos.w);\n"
	"    \n"
	"    vec3 res = mix(res1, res2, step(c_df(E, res1), c_df(E, res2)));\n"
	"\n"
	"    FragColor = vec4(res, 1.0);\n"
	"}\n"
	"\n";

#endif
